#!/bin/bash

INSTANCE=$(tmux ls | grep elastic | sed 's/\s/ /g')

if [ -n "$INSTANCE" ]
then
	echo "Already running: $INSTANCE"
else
	mkdir -p /vagrant/logs

	tmux a -t elastic
	echo "-----------------------------------------------------------------------------------------------------------"
	echo " => Started $(tmux ls | grep elastic | sed 's/\s/ /g')"
	echo "-----------------------------------------------------------------------------------------------------------"
fi
